# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AMPObjCUIStudy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  # Pods for AMPObjCUIStudy

  target 'AMPObjCUIStudyTests' do
    inherit! :search_paths
	pod 'Kiwi'
    # Pods for testing
  end

end
